version: '3.3'

services:
  app-nginx:
    build:
      context: .
      dockerfile: docker/app/nginx.dockerfile
    container_name: app-nginx
    volumes:
      - ./main:/var/www/app
      - ./docker/nginx-reverse-proxy/ssl:/etc/nginx/ssl
    depends_on:
      - nginx-reverse-proxy
    networks:
      net:
        ipv4_address: 172.21.1.2

  app-php:
    build:
      context: .
      dockerfile: docker/app/php-fpm.dockerfile
    container_name: app-php
    volumes:
      - ./main:/var/www/app
      - ./docker/app/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    links:
      - mysql
#      - mailcatcher
    depends_on:
      - app-nginx
    networks:
      net:
        ipv4_address: 172.21.1.3

  queue-worker-php:
    build:
      context: .
      dockerfile: docker/queue-worker/php-fpm.dockerfile
    container_name: qw-php
    volumes:
      - ./main:/var/www/qw
    depends_on:
      - rabbitmq
    networks:
      net:
        ipv4_address: 172.21.1.4

  ws-php:
    build:
      context: .
      dockerfile: docker/ws/php-fpm.dockerfile
    container_name: ws-php
    volumes:
      - ./main:/var/www/ws
    expose:
      - 6001
    networks:
      net:
        ipv4_address: 172.21.1.5

#  cron:
#    build:
#      context: .
#      dockerfile: docker/cron/php-alpine.dockerfile
#    container_name: cron-php
#    volumes:
#      - ./main:/var/www/cron
#    networks:
#      net:
#        ipv4_address: 172.21.1.6

  nginx-reverse-proxy:
    build:
      context: .
      dockerfile: docker/nginx-reverse-proxy/nginx.dockerfile
    container_name: nginx-reverse-proxy
    volumes:
      - ./docker/nginx-reverse-proxy/ssl:/etc/nginx/ssl
    ports:
      - 443:443
      - 6001:6001
    networks:
      net:
        ipv4_address: 172.21.1.251

  mysql:
    build:
      context: .
      dockerfile: docker/app/mysql.dockerfile
    container_name: app-mysql
    volumes:
      - ./Makefile:/Makefile
    ports:
      - 127.0.0.1:53307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fa_db
    networks:
      net:
        ipv4_address: 172.21.1.252

#  mailcatcher:
#    image: yappabe/mailcatcher
#    container_name: fa-mailcatcher
#    ports:
#      - 1025:1025
#      - 1080:1080
#    networks:
#      net:
#        ipv4_address: 172.21.1.253
#
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      # HTTP management UI
      - 15672:15672
    expose:
      # AMQP protocol port
      - 5672
    networks:
      net:
        ipv4_address: 172.21.1.254

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/24"
