version: '3.3'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    container_name: fa-nginx
    volumes:
      - ./:/var/www/freeArtist
    ports:
      - 127.0.0.1:8080:80
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php-fpm.dockerfile
    container_name: fa-php
    volumes:
      - ./:/var/www/freeArtist
      - ./docker/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    links:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: docker/mysql.dockerfile
    container_name: fa-mysql
    volumes:
      - ./Makefile:/Makefile
    ports:
      - 127.0.0.1:53307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fa_db
