version: '3.3'

services:
  app-nginx:
    build:
      context: .
      dockerfile: docker/app/nginx.dockerfile
    container_name: app-nginx
    volumes:
      - ./main:/var/www/app
      - ./docker/nginx-reverse-proxy/ssl:/etc/nginx/ssl
    depends_on:
      - nginx-reverse-proxy
    networks:
      net:
        ipv4_address: 172.21.1.2

  app-php:
    build:
      context: .
      dockerfile: docker/app/php-fpm.dockerfile
    container_name: app-php
    volumes:
      - ./main:/var/www/app
      - ./docker/app/php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    links:
      - pg
#      - mailcatcher
    expose:
      - 6001
    depends_on:
      - app-nginx
    networks:
      net:
        ipv4_address: 172.21.1.3

  queue-worker-php:
    build:
      context: .
      dockerfile: docker/queue-worker/php-fpm.dockerfile
    container_name: qw-php
    volumes:
      - ./qw:/var/www/qw
    depends_on:
      - rabbitmq
    networks:
      net:
        ipv4_address: 172.21.1.4

  nginx-reverse-proxy:
    build:
      context: .
      dockerfile: docker/nginx-reverse-proxy/nginx.dockerfile
    container_name: nginx-reverse-proxy
    volumes:
      - ./docker/nginx-reverse-proxy/ssl:/etc/nginx/ssl
    ports:
      - 443:443
      - 6001:6001
    networks:
      net:
        ipv4_address: 172.21.1.251

  pg:
    build:
      context: .
      dockerfile: docker/app/pg.dockerfile
    container_name: app-pg
    volumes:
      - ./Makefile:/Makefile
#       Раскоментить если нужно запускать БД из дампа
#      - ./dump:/dump
#      - ./dump:/docker-entrypoint-initdb.d:ro
    ports:
      - 53307:5432
    #POSTGRES_USER - должен быть таким же как OWNER в импортируемом дампе
    #LC_* - должны быть такие же как в дампе. Дефолтная - en_US. Своя устанавливается в докерфайле
    environment:
      - POSTGRES_DB=fa_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - LC_COLLATE=ru_RU.UTF-8
#      - LC_CTYPE=ru_RU.UTF-8
    networks:
      net:
        ipv4_address: 172.21.1.252

#  mailcatcher:
#    image: yappabe/mailcatcher
#    container_name: fa-mailcatcher
#    ports:
#      - 1025:1025
#      - 1080:1080
#    networks:
#      net:
#        ipv4_address: 172.21.1.253
#
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      # HTTP management UI
      - 15672:15672
    expose:
      # AMQP protocol port
      - 5672
    networks:
      net:
        ipv4_address: 172.21.1.254

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/24"
