export const RELATION_REQUEST_STATUSES = {
	PENDING: 1,
	ACCEPTED: 2,
	REJECTED_BY_RECIPIENT: 3,
	CANCELED_BY_CONTRIBUTOR: 4
}

export const RELATION_REQUEST_STATUS_NAMES = {
	[RELATION_REQUEST_STATUSES.PENDING]: "На рассмотрении",
	[RELATION_REQUEST_STATUSES.ACCEPTED]: "Принято",
	[RELATION_REQUEST_STATUSES.REJECTED_BY_RECIPIENT]: "Отказано получателем",
	[RELATION_REQUEST_STATUSES.CANCELED_BY_CONTRIBUTOR]: "Отмена",
}
